#!/bin/bash -e

#fasta_hyb2_formatting -i human.fasta

# parsing command line options
while getopts "i:" OPTION
do
     case $OPTION in
         i) DB=$OPTARG ;;
         ?)

             echo "incorrect option"
             exit 0
             ;;
     esac
done

sed 's/_/-/g;s/protein-coding/mRNA/g;s/|/_/g;s/__/_unknown_/g' $DB > ${DB/.fasta/.tmp}
awk '{if(NR==1) {print $0} else {if($0 ~ /^>/) {print "\n"$0} else {printf $0}}}' ${DB/.fasta/.tmp} > ${DB/.fasta/.tmp2}
sed '/unknown/,+1 d;/pseudogene/,+1 d' ${DB/.fasta/.tmp2} > ${DB/.fasta/.hyb.fasta}

rm ${DB/.fasta/.tmp2} ${DB/.fasta/.tmp}
