#!/bin/bash 

# Step 1: Move file and set VARNAcmd.jar path
mv bin/environment.yml .
echo "$PWD"/VARNA/build/jar/VARNAcmd.jar > bin/VARNA.dir
echo 'cat '"$PWD"/bin/VARNA.dir >> bin/VARNAcmd.sh

# Step 2: Add hyb2 to PATH
# echo 'export PATH=$PATH:'"$PWD/bin" >> ~/.zshrc
# source ~/.zshrc

# Function to source the appropriate configuration file and export a new PATH
source_config_file() {
    case "$SHELL" in
        */zsh)
            echo 'export PATH=$PATH:'"$PWD/bin" >> ~/.zshrc
            echo 'alias Hyb2='"$PWD" >> ~/.zshrc
            echo "Sourcing .zshrc"
            source ~/.zshrc
            ;;
        */bash)
            echo 'export PATH=$PATH:'"$PWD/bin" >> ~/.bashrc
            echo 'alias Hyb2='"$PWD" >> ~/.bashrc
            echo "Sourcing .bashrc"
            if [ -f ~/.bashrc ]; then
                source ~/.bashrc
            fi
            ;;
        *)
            echo "Unknown shell: $SHELL. Please source the correct configuration file manually to export to PATH."
            ;;
    esac
}

source_config_file

# Step 3: Create and activate the hyb2 conda environments
echo "Creating hyb2 conda environments"
conda env create -f bin/hyb2_macOS.yml
source $(conda info --base)/etc/profile.d/conda.sh
conda activate hyb2_macOS

# Step 5: Initialize renv (creates a new renv.lock file)
# echo "Ignore warnings: package(s) were not installed successfully, reinstall before snapshotting the lockfile."
Rscript -e 'renv::init()'

# Step 6: Replace the new renv.lock with the one in hyb2/bin
cp bin/renv.lock .

# Step 7: Restore the R environment using renv
Rscript -e 'renv::restore()'

# Step 8: Add hyb2 to PATH in R
Rscript -e 'Sys.setenv(PATH=paste(Sys.getenv("PATH"), "'$PWD/bin'", sep=":"))'

cp -r renv ~/
cp bin/hyb2_shiny.R ~/
rm .Rprofile

echo "Hyb2 Installation Complete"
