#!/bin/bash

if [ $# -ne 1 ]; then
echo "usage: $0 input.fasta"
exit 1
fi

if [ ! -e $1 ]; then
echo "usage: $0 input.fasta"
echo "error: $1 file not found"
exit 1
fi

bowtie2-build $1 ${1/.fasta/}
fasta2tab.awk $1 > ${1/fasta/tab}

